### ISSUE TITLE
"sys.path.insert" error

### ISSUE THREAD

**Issue by texx00** [johnbryanmoore/VL53L0X_rasp_python#19]
I tried to load the library by using `sys.path.insert` but there was an error at runtime:
`File "main.py", line 6, in <module>
    import VL53L0X  `
`  File "/home/pi/*MyPath*/lib/VL53L0X_rasp_python/python/VL53L0X.py", line 68, in <module>
    tof_lib = CDLL("../bin/vl53l0x_python.so")`
 ` File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)`
`OSError: ../bin/vl53l0x_python.so: cannot open shared object file: No such file or directory`

[I tried to add the path to the libraries environment variable](https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path) and other things but I was not able to fix it.

I did find a workaround by changing the `VL53L0X.py` library file like this on line 67:
`# Load VL53L0X shared lib` 
`import os `
`dirname = os.path.dirname(__file__)`
`filename = os.path.join(dirname, "../bin/vl53l0x_python.so")`
`tof_lib = CDLL(filename)`

I've never worked/used ctypes and I'm sure this is not the best solution but I cannot understand if I'm doing something wrong or if it is really a library issue.

**Comment by MohammedKhaliid** [comment]
I have the same issue here and can't solve it too, so have you found any solution to that?

**Comment by texx00** [comment]
To make it work I needed to change it like this:

> I did find a workaround by changing the VL53L0X.py library file like this on line 67:
```# Load VL53L0X shared lib
import os 
dirname = os.path.dirname(__file__)
filename = os.path.join(dirname, "../bin/vl53l0x_python.so")
tof_lib = CDLL(filename)```

**Comment by MohammedKhaliid** [comment]
```
Traceback (most recent call last):
  File "VL53L0X.py", line 71, in <module>
    tof_lib = CDLL(filename)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../bin/vl53l0x_python.so: cannot open shared object file: No such file or directory
```
Almost the same error after the editing !!

could you help me with that?

**Comment by texx00** [comment]
Are you building the library with make? Check if you have the .so file in the bin folder... This is the only idea I have

**Comment by MohammedKhaliid** [comment]
I didn't find the .so file in bin folder although I have made all the steps mentioned in the post, so do you have any idea how to add this file and solve this problem?
Thanks in advance

**Comment by texx00** [comment]
You need to be sure the make command is running correctly and the file should be created automatically. I never worked with ctypes thus I do not know more than this. Make is compiling the library from c code into the .so file. You may look around for more info about make... Maybe you can change some options or enable some logging... Not sure though

**Comment by MohammedKhaliid** [comment]
Ok, thank you for your help.

**Comment by Gerrit404** [comment]
> To make it work I needed to change it like this:
> 
> > I did find a workaround by changing the VL53L0X.py library file like this on line 67:
> 
> ```
> import os 
> dirname = os.path.dirname(__file__)
> filename = os.path.join(dirname, "../bin/vl53l0x_python.so")
> tof_lib = CDLL(filename)```
> ```

Thanks! I had issues using this package as a subfolder in my program. My executing main is two folders above this package folder. By adjusting the VL53L0X.py with your settings it works

**Comment by DansDesigns** [comment]
I tried the solution mentioned above but that didnt work for me (NanoPi Neo) so i put the explicit path into line 67:
```
# Load VL53L0X shared lib
tof_lib = CDLL("/home/pi/VL53L0X_rasp_python/bin/vl53l0x_python.so")
```
and this seemed to work however i now get the following issue:
```
VL53L0X Start Ranging Object 0 Address 0x29

Call of VL53L0X_DataInit
API Status: -20 : Control Interface Error
Timing 20 ms
Call of VL53L0X_StopMeasurement
API Status: -20 : Control Interface Error
```

solved it by switching to another sensor..
